module.exports = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/legacy/setupTests.js', '<rootDir>/test/setup.js'],
  testMatch: ['<rootDir>/test/**/*.{test,spec}.{js,jsx,ts,tsx}'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/coverage/'],
  moduleNameMapper: { '\\.(css|less|scss|sass)$': 'identity-obj-proxy' },
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json'],
  transform: { '^.+\\.(js|jsx)$': 'babel-jest', '^.+\\.(ts|tsx)$': 'ts-jest' },
  transformIgnorePatterns: ['node_modules/(?!(iconoir-react)/)'],
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/**/index.{js,ts}', '!src/**/*.d.ts'],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  coverageThreshold: { global: { branches: 80, functions: 80, lines: 80, statements: 80 } },
  maxWorkers: '50%',
  cacheDirectory: '.jest-cache',
  clearMocks: true,
  testTimeout: 10000,
  preset: 'ts-jest/presets/js-with-ts',
  globals: { 'ts-jest': { tsconfig: { jsx: 'react-jsx' } } }
};